remote_theme: just-the-docs/just-the-docs
title: LDT DevDocs
description: Bookmark this to keep an eye on my project updates!

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

ec_docs:
  collections:
    ec:
      name: EC Docs
